services:
  mqtt:
    image: ${MQTT_IMAGE}
    ports:
      - 1883:1883
#      - 9001:9001
    volumes:
      - mqtt_data:/mosquitto/data
      - ./docker/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - ./docker/mqtt/passwords.txt:/mosquitto/config/passwords.txt #default user admin:adminle

  influxdb:
    image: ${INFLUX_IMAGE}
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUX_ADMIN_USER}
      - INFLUXDB_ADMIN_USER_TOKEN=${INFLUX_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUX_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUX_USER_PASSWORD}
      - INFLUXDB_DB=${INFLUX_DB}
    volumes:
      - influxdb_data:/bitnami/influxdb

  www:
    image: ${NGINX_IMAGE}
    ports:
      - "8888:80"
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html

  php:
    image: ${PHP_IMAGE}
    depends_on:
      - influxdb
      - mqtt
    volumes:
      - ./:/usr/share/nginx/html



volumes:
  mqtt_data:
  influxdb_data:
